# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_serv.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('CollegeID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('CollegeName', models.CharField(editable=False, max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=25)),
                ('Venue', models.TextField(blank=True, max_length=300, null=True)),
                ('EventDateTime', models.DateTimeField(blank=True, null=True)),
                ('MinPlayersReq', models.IntegerField(default=0)),
                ('MaxPlayersReq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PersistentNotification',
            fields=[
                ('NotificationID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NotificationText', models.CharField(max_length=200)),
                ('Priority', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PlayerName', models.CharField(max_length=40)),
                ('PlayerImage', models.ImageField(blank=True, null=True, upload_to=rest_serv.models.upload_to)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('CollegeRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_serv.College')),
                ('UserRef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamRef', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CoachName', models.CharField(blank=True, max_length=40, null=True)),
                ('CollegeRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_serv.College')),
                ('EventRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_serv.Event')),
                ('Leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='rest_serv.Player')),
                ('Members', models.ManyToManyField(related_name='team_members', to='rest_serv.Player')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('NotificationID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NotificationText', models.CharField(max_length=200)),
                ('Priority', models.IntegerField(blank=True, default=1)),
                ('UserToNotify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_serv.Player')),
            ],
        ),
    ]
