# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_serv', '0003_auto_20170608_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
